service: serverless
provider:
  name: aws
  runtime: nodejs20.x

  stage: dev
  region: eu-north-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # in second
    memorySize: 120 # in MBs
